<?php

$languagesList = '{
  "aa": ["Afar", "Afar", "ern"],
  "ab": ["Abkhazian", "Аҧсшәа", "abk"],
  "ae": ["Avestan", "𐎧𐏁𐎗𐏁𐎠", "ave"],
  "af": ["Afrikaans", "Afrikaans", "zar"],
  "ak": ["Akan", "Akan", "ghs"],
  "am": ["Amharic", "አማርኛ", "etb"],
  "an": ["Aragonese", "Aragonés", "eur"],
  "ar": ["Arabic", "العربية", "sar"],
  "as": ["Assamese", "অসমীয়া", "inr"],
  "av": ["Avaric", "Авaр", "azn"],
  "ay": ["Aymara", "Aymara", "bob"],
  "az": ["Azerbaijani", "azərbaycan", "azn"],
  "ba": ["Bashkir", "Башҡорташ", "rub"],
  "be": ["Belarusian", "Беларуская", "byn"],
  "bg": ["Bulgarian", "Български", "bgn"],
  "bi": ["Bislama", "Bislama", "vuv"],
  "bm": ["Bambara", "Bamanankan", "xof"],
  "bn": ["Bengali", "বাংলা", "bdt"],
  "bo": ["Tibetan", "བོད་ཡིག", "cny"],
  "br": ["Breton", "Brezhoneg", "eur"],
  "bs": ["Bosnian", "Bosanski", "bam"],
  "ca": ["Catalan", "Català", "eur"],
  "ce": ["Chechen", "Нохчийн", "rub"],
  "ch": ["Chamorro", "Chamoru", "usd"],
  "co": ["Corsican", "Corsu", "eur"],
  "cr": ["Cree", "ᓀᐦᐃᔭᐤ", "cad"],
  "cs": ["Czech", "Čeština", "czk"],
  "cu": ["Church Slavic", "Црьъкьскъй", "rub"],
  "cv": ["Chuvash", "Чӑваш", "rub"],
  "cy": ["Welsh", "Cymraeg", "gbp"],
  "da": ["Danish", "Dansk", "dkk"],
  "de": ["German", "Deutsch", "eur"],
  "dv": ["Divehi", "ދިވެހި", "mvr"],
  "dz": ["Dzongkha", "རྫོང་ཁ", "npr"],
  "ee": ["Ewe", "Eʋegbe", "xcd"],
  "el": ["Greek", "Ελληνικά", "eur"],
  "en": ["English", "English", "usd"],
  "eo": ["Esperanto", "Esperanto", "usd"],
  "es": ["Spanish", "Español", "eur"],
  "et": ["Estonian", "Eesti", "eur"],
  "eu": ["Basque", "Euskara", "eur"],
  "fa": ["Persian", "فارسی", "irr"],
  "ff": ["Fulah", "Fulfulde", "xof"],
  "fi": ["Finnish", "Suomi", "eur"],
  "fj": ["Fijian", "Na Vosa Vakaviti", "fjd"],
  "fo": ["Faroese", "Føroyskt", "dkk"],
  "fr": ["French", "Français", "eur"],
  "fy": ["Western Frisian", "Frysk", "fr"],
  "ga": ["Irish", "Gaeilge", "eu"],
  "gd": ["Gaelic", "Gàidhlig", "gbp"],
  "gl": ["Galician", "Galego", "eur"],
  "gn": ["Guarani", "Aña", "pyg"],
  "gu": ["Gujarati", "ગુજરાતી", "inr"],
  "gv": ["Manx", "Gaelg", "gbp"],
  "ha": ["Hausa", "هَوُسَ", "ngn"],
  "he": ["Hebrew", "עברית", "ils"],
  "hi": ["Hindi", "हिन्दी", "inr"],
  "ho": ["Hiri Motu", "Hiri Motu", "pgk"],
  "hr": ["Croatian", "Hrvatski", "hrk"],
  "ht": ["Haitian", "Kreyòl", "htg"],
  "hu": ["Hungarian", "Magyar", "huf"],
  "hy": ["Armenian", "Հայերեն", "amd"],
  "hz": ["Herero", "Otjiherero", "nad"],
  "ia": ["Interlingua", "Interlingua", "usd"],
  "id": ["Indonesian", "Bahasa Indonesia", "idr"],
  "ie": ["Interlingue", "Interlingue", "usd"],
  "ig": ["Igbo", "Igbo", "ngn"],
  "ii": ["Sichuan Yi", "ꑿꑭꊟ", "cny"],
  "ik": ["Inupiaq", "Iñupiatun", "usd"],
  "io": ["Ido", "Ido", "usd"],
  "is": ["Icelandic", "Íslenska", "isk"],
  "it": ["Italian", "Italiano", "eur"],
  "iu": ["Inuktitut", "Inuktitut", "cad"],
  "ja": ["Japanese", "日本語", "jpy"],
  "jv": ["Javanese", "Basa Jawa", "idr"],
  "ka": ["Georgian", "ქართული", "gel"],
  "kg": ["Kongo", "KiKongo", "xcd"],
  "ki": ["Kikuyu", "Gĩkũyũ", "kes"],
  "kj": ["Kuanyama", "Oiyambaa", "aed"],
  "kk": ["Kazakh", "Қазақ тілі", "kzt"],
  "kl": ["Kalaallisut", "Kalaallisut", "dkk"],
  "km": ["Central Khmer", "ខ្មែរ", "khk"],
  "kn": ["Kannada", "ಕನ್ನಡ", "inr"],
  "ko": ["Korean", "한국어", "krw"],
  "kr": ["Kanuri", "Kanuri", "ngn"],
  "ks": ["Kashmiri", "कश्मीरी", "inr"],
  "ku": ["Kurdish", "Kurdî", "try"],
  "kv": ["Komi", "Коми", "rub"],
  "kw": ["Cornish", "Kernewek", "gbp"],
  "ky": ["Kirghiz", "Кыргызча", "kyd"],
  "la": ["Latin", "Latina", "usd"],
  "lb": ["Luxembourgish", "Lëtzebuergesch", "eur"],
  "lg": ["Ganda", "Luganda", "ugx"],
  "li": ["Limburgan", "Limburgs", "eur"],
  "ln": ["Lingala", "Lingála", "cdf"],
  "lo": ["Lao", "ລາວ", "lak"],
  "lt": ["Lithuanian", "LIetuvių", "eur"],
  "lu": ["Luba-Katanga", "Tshiluba", "CDF"],
  "lv": ["Latvian", "Latviešu", "EUR"],
  "mg": ["Malagasy", "Malagasy", "MGA"],
  "mh": ["Marshallese", "Marshallese", "AUD"],
  "mi": ["Maori", "Māori", "NZD"],
  "mk": ["Macedonian", "Македонски", "MKD"],
  "ml": ["Malayalam", "മലയാളം", "INR"],
  "mn": ["Mongolian", "Монгол", "MNT"],
  "mr": ["Marathi", "मराठी", "INR"],
  "ms": ["Malay", "Bahasa Melayu", "MYR"],
  "mt": ["Maltese", "Malti", "EUR"],
  "my": ["Burmese", "မြန်မာဘာသာ", "MMK"],
  "na": ["Nauru", "Nauruan", "AUD"],
  "nb": ["Bokmål, Norwegian", "Bokmål", "NOK"],
  "nd": ["Ndebele, North", "Ndebele", "ZAR"],
  "ne": ["Nepali", "नेपाली", "NPR"],
  "ng": ["Ndonga", "Oshindonga", "NAD"],
  "nl": ["Dutch", "Nederlands", "EUR"],
  "nn": ["Norwegian Nynorsk", "Nynorsk", "NOK"],
  "no": ["Norwegian", "Norsk", "NOK"],
  "nr": ["Ndebele, South", "Ndebele", "ZAR"],
  "nv": ["Navajo", "Diné bizaad", "USD"],
  "ny": ["Chichewa", "Chichewa", "MWK"],
  "oc": ["Occitan", "Occitan", "EUR"],
  "oj": ["Ojibwa", "ᐊᓈᑕᐦᑕ", "CAD"],
  "om": ["Oromo", "Afaan Oromoo", "ETB"],
  "or": ["Oriya", "ଓଡ଼ିଆ", "INR"],
  "os": ["Ossetian", "Ирон", "RUB"],
  "pa": ["Panjabi", "ਪੰਜਾਬੀ", "INR"],
  "pi": ["Pali", "पास्नु", "N/A"],
  "pl": ["Polish", "Polski", "PLN"],
  "ps": ["Pushto", "پښتو", "AFN"],
  "pt": ["Portuguese", "Português", "EUR"],
  "qu": ["Quechua", "Runa Simi", "PEN"],
  "rm": ["Romansh", "Romansh", "CHF"],
  "rn": ["Rundi", "Ikirundi", "BIF"],
  "ro": ["Romanian", "Română", "RON"],
  "ru": ["Russian", "Русский", "RUB"],
  "rw": ["Kinyarwanda", "Ikinyarwanda", "RWF"],
  "sa": ["Sanskrit", "संस्कृतम्", "INR"],
  "sc": ["Sardinian", "Sardu", "EUR"],
  "sd": ["Sindhi", "سنڌي", "PKR"],
  "se": ["Northern Sami", "Davvisámegiella", "SEK"],
  "sg": ["Sango", "Sango", "XAF"],
  "si": ["Sinhala", "සිංහල", "LKR"],
  "sk": ["Slovak", "Slovenčina", "EUR"],
  "sl": ["Slovenian", "Slovenščina", "EUR"],
  "sm": ["Samoan", "Gagana Samoa", "WST"],
  "sn": ["Shona", "ChiShona", "USD"],
  "so": ["Somali", "Soomaaliga", "SOS"],
  "sq": ["Albanian", "Shqip", "ALL"],
  "sr": ["Serbian", "Српски", "RSD"],
  "ss": ["Swati", "siSwati", "SZL"],
  "st": ["Sotho, Southern", "Sesotho", "ZAR"],
  "su": ["Sundanese", "Basa Sunda", "IDR"],
  "sv": ["Swedish", "Svenska", "SEK"],
  "sw": ["Swahili", "Kiswahili", "KES"],
  "ta": ["Tamil", "தமிழ்", "INR"],
  "te": ["Telugu", "తెలుగు", "INR"],
  "tg": ["Tajik", "Тоҷикӣ", "TJS"],
  "th": ["Thai", "ไทย", "THB"],
  "ti": ["Tigrinya", "ትግርኛ", "ERN"],
  "tk": ["Turkmen", "Türkmençe", "TMT"],
  "tl": ["Tagalog", "Wikang Tagalog", "PHP"],
  "tn": ["Tswana", "Setswana", "ZAR"],
  "to": ["Tonga", "Faka Tonga", "TOP"],
  "tr": ["Turkish", "Türkçe", "TRY"],
  "ts": ["Tsonga", "Xitsonga", "ZAR"],
  "tt": ["Tatar", "Татарча", "RUB"],
  "tw": ["Twi", "Twi", "GHS"],
  "ty": ["Tahitian", "Reo Tahiti", "XPF"],
  "ug": ["Uighur", "ئۇيغۇرچە", "CNY"],
  "uk": ["Ukrainian", "Українська", "UAH"],
  "ur": ["Urdu", "اردو", "PKR"],
  "uz": ["Uzbek", "Oʻzbekcha", "UZS"],
  "ve": ["Venda", "Tshivenḓa", "ZAR"],
  "vi": ["Vietnamese", "Tiếng Việt", "VND"],
  "vo": ["Volapük", "Volapük", "UNK"],
  "wa": ["Walloon", "Walon", "EUR"],
  "wo": ["Wolof", "Wolof", "XOF"],
  "xh": ["Xhosa", "isiXhosa", "ZAR"],
  "yi": ["Yiddish", "ייִדיש", "ILS"],
  "yo": ["Yoruba", "Yorùbá", "NGN"],
  "za": ["Zhuang", "Cuengh", "CNY"],
  "zh": ["Chinese", "中文", "CNY"],
  "zu": ["Zulu", "isiZulu", "ZAR"]
}';

