<?php

$languagesList = '{
  "aa": ["Afar", "Afar"],
  "ab": ["Abkhazian", "Аҧсшәа"],
  "ae": ["Avestan", "𐎧𐏁𐎗𐏁𐎠"],
  "af": ["Afrikaans", "Afrikaans"],
  "ak": ["Akan", "Akan"],
  "am": ["Amharic", "አማርኛ"],
  "an": ["Aragonese", "Aragonés"],
  "ar": ["Arabic", "العربية"],
  "as": ["Assamese", "অসমীয়া"],
  "av": ["Avaric", "Авaр"],
  "ay": ["Aymara", "Aymara"],
  "az": ["Azerbaijani", "azərbaycan"],
  "ba": ["Bashkir", "Башҡорташ"],
  "be": ["Belarusian", "Беларуская"],
  "bg": ["Bulgarian", "Български"],
  "bi": ["Bislama", "Bislama"],
  "bm": ["Bambara", "Bamanankan"],
  "bn": ["Bengali", "বাংলা"],
  "bo": ["Tibetan", "བོད་ཡིག"],
  "br": ["Breton", "Brezhoneg"],
  "bs": ["Bosnian", "Bosanski"],
  "ca": ["Catalan", "Català"],
  "ce": ["Chechen", "Нохчийн"],
  "ch": ["Chamorro", "Chamoru"],
  "co": ["Corsican", "Corsu"],
  "cr": ["Cree", "ᓀᐦᐃᔭᐤ"],
  "cs": ["Czech", "Čeština"],
  "cu": ["Church Slavic", "Црьъкьскъй"],
  "cv": ["Chuvash", "Чӑваш"],
  "cy": ["Welsh", "Cymraeg"],
  "da": ["Danish", "Dansk"],
  "de": ["German", "Deutsch"],
  "dv": ["Divehi", "ދިވެހި"],
  "dz": ["Dzongkha", "རྫོང་ཁ"],
  "ee": ["Ewe", "Eʋegbe"],
  "el": ["Greek", "Ελληνικά"],
  "en": ["English", "English"],
  "eo": ["Esperanto", "Esperanto"],
  "es": ["Spanish", "Español"],
  "et": ["Estonian", "Eesti"],
  "eu": ["Basque", "Euskara"],
  "fa": ["Persian", "فارسی"],
  "ff": ["Fulah", "Fulfulde"],
  "fi": ["Finnish", "Suomi"],
  "fj": ["Fijian", "Na Vosa Vakaviti"],
  "fo": ["Faroese", "Føroyskt"],
  "fr": ["French", "Français"],
  "fy": ["Western Frisian", "Frysk"],
  "ga": ["Irish", "Gaeilge"],
  "gd": ["Gaelic", "Gàidhlig"],
  "gl": ["Galician", "Galego"],
  "gn": ["Guarani", "Aña"],
  "gu": ["Gujarati", "ગુજરાતી"],
  "gv": ["Manx", "Gaelg"],
  "ha": ["Hausa", "هَوُسَ"],
  "he": ["Hebrew", "עברית"],
  "hi": ["Hindi", "हिन्दी"],
  "ho": ["Hiri Motu", "Hiri Motu"],
  "hr": ["Croatian", "Hrvatski"],
  "ht": ["Haitian", "Kreyòl"],
  "hu": ["Hungarian", "Magyar"],
  "hy": ["Armenian", "Հայերեն"],
  "hz": ["Herero", "Otjiherero"],
  "ia": ["Interlingua", "Interlingua"],
  "id": ["Indonesian", "Bahasa Indonesia"],
  "ie": ["Interlingue", "Interlingue"],
  "ig": ["Igbo", "Igbo"],
  "ii": ["Sichuan Yi", "ꑿꑭꊟ"],
  "ik": ["Inupiaq", "Iñupiatun"],
  "io": ["Ido", "Ido"],
  "is": ["Icelandic", "Íslenska"],
  "it": ["Italian", "Italiano"],
  "iu": ["Inuktitut", "Inuktitut"],
  "ja": ["Japanese", "日本語"],
  "jv": ["Javanese", "Basa Jawa"],
  "ka": ["Georgian", "ქართული"],
  "kg": ["Kongo", "KiKongo"],
  "ki": ["Kikuyu", "Gĩkũyũ"],
  "kj": ["Kuanyama", "Oiyambaa"],
  "kk": ["Kazakh", "Қазақ тілі"],
  "kl": ["Kalaallisut", "Kalaallisut"],
  "km": ["Central Khmer", "ខ្មែរ"],
  "kn": ["Kannada", "ಕನ್ನಡ"],
  "ko": ["Korean", "한국어"],
  "kr": ["Kanuri", "Kanuri"],
  "ks": ["Kashmiri", "कश्मीरी"],
  "ku": ["Kurdish", "Kurdî"],
  "kv": ["Komi", "Коми"],
  "kw": ["Cornish", "Kernewek"],
  "ky": ["Kirghiz", "Кыргызча"],
  "la": ["Latin", "Latina"],
  "lb": ["Luxembourgish", "Lëtzebuergesch"],
  "lg": ["Ganda", "Luganda"],
  "li": ["Limburgan", "Limburgs"],
  "ln": ["Lingala", "Lingála"],
  "lo": ["Lao", "ລາວ"],
  "lt": ["Lithuanian", "LIetuvių"],
  "lu": ["Luba-Katanga", "Tshiluba"],
  "lv": ["Latvian", "Latviešu"],
  "mg": ["Malagasy", "Malagasy"],
  "mh": ["Marshallese", "Marshallese"],
  "mi": ["Maori", "Māori"],
  "mk": ["Macedonian", "Македонски"],
  "ml": ["Malayalam", "മലയാളം"],
  "mn": ["Mongolian", "Монгол"],
  "mr": ["Marathi", "मराठी"],
  "ms": ["Malay", "Bahasa Melayu"],
  "mt": ["Maltese", "Malti"],
  "my": ["Burmese", "မြန်မာဘာသာ"],
  "na": ["Nauru", "Nauruan"],
  "nb": ["Bokmål, Norwegian", "Bokmål"],
  "nd": ["Ndebele, North", "Ndebele"],
  "ne": ["Nepali", "नेपाली"],
  "ng": ["Ndonga", "Oshindonga"],
  "nl": ["Dutch", "Nederlands"],
  "nn": ["Norwegian Nynorsk", "Nynorsk"],
  "no": ["Norwegian", "Norsk"],
  "nr": ["Ndebele, South", "Ndebele"],
  "nv": ["Navajo", "Diné bizaad"],
  "ny": ["Chichewa", "Chichewa"],
  "oc": ["Occitan", "Occitan"],
  "oj": ["Ojibwa", "ᐊᓈᑕᐦᑕ"],
  "om": ["Oromo", "Afaan Oromoo"],
  "or": ["Oriya", "ଓଡ଼ିଆ"],
  "os": ["Ossetian", "Ирон"],
  "pa": ["Panjabi", "ਪੰਜਾਬੀ"],
  "pi": ["Pali", "पास्नु"],
  "pl": ["Polish", "Polski"],
  "ps": ["Pushto", "پښتو"],
  "pt": ["Portuguese", "Português"],
  "qu": ["Quechua", "Runa Simi"],
  "rm": ["Romansh", "Romansh"],
  "rn": ["Rundi", "Ikirundi"],
  "ro": ["Romanian", "Română"],
  "ru": ["Russian", "Русский"],
  "rw": ["Kinyarwanda", "Ikinyarwanda"],
  "sa": ["Sanskrit", "संस्कृतम्"],
  "sc": ["Sardinian", "Sardu"],
  "sd": ["Sindhi", "سنڌي"],
  "se": ["Northern Sami", "Davvisámegiella"],
  "sg": ["Sango", "Sango"],
  "si": ["Sinhala", "සිංහල"],
  "sk": ["Slovak", "Slovenčina"],
  "sl": ["Slovenian", "Slovenščina"],
  "sm": ["Samoan", "Gagana Samoa"],
  "sn": ["Shona", "ChiShona"],
  "so": ["Somali", "Soomaaliga"],
  "sq": ["Albanian", "Shqip"],
  "sr": ["Serbian", "Српски"],
   "ss": ["Swati", "siSwati"],
  "st": ["Sotho, Southern", "Sesotho"],
  "su": ["Sundanese", "Basa Sunda"],
  "sv": ["Swedish", "Svenska"],
  "sw": ["Swahili", "Kiswahili"],
  "ta": ["Tamil", "தமிழ்"],
  "te": ["Telugu", "తెలుగు"],
  "tg": ["Tajik", "Тоҷикӣ"],
  "th": ["Thai", "ไทย"],
  "ti": ["Tigrinya", "ትግርኛ"],
  "tk": ["Turkmen", "Türkmençe"],
  "tl": ["Tagalog", "Wikang Tagalog"],
  "tn": ["Tswana", "Setswana"],
  "to": ["Tonga", "Faka Tonga"],
  "tr": ["Turkish", "Türkçe"],
  "ts": ["Tsonga", "Xitsonga"],
  "tt": ["Tatar", "Татарча"],
  "tw": ["Twi", "Twi"],
  "ty": ["Tahitian", "Reo Tahiti"],
  "ug": ["Uighur", " ئۇيغۇرچە"],
  "uk": ["Ukrainian", "Українська"],
  "ur": ["Urdu", "اردو"],
  "uz": ["Uzbek", "Oʻzbekcha"],
  "ve": ["Venda", "Tshivenḓa"],
  "vi": ["Vietnamese", "Tiếng Việt"],
  "vo": ["Volapük", "Volapük"],
  "wa": ["Walloon", "Walon"],
  "wo": ["Wolof", "Wolof"],
  "xh": ["Xhosa", "isiXhosa"],
  "yi": ["Yiddish", "ייִדיש"],
  "yo": ["Yoruba", "Yorùbá"],
  "za": ["Zhuang", "Cuengh"],
  "zh": ["Chinese", "中文"],
  "zu": ["Zulu", "isiZulu"]
}';

